name: {{name.snakeCase()}}
description: Feature {{classname.pascalCase()}} (couche domain).
version: 0.0.1
publish_to: none

environment:
  flutter: ">=3.27.0"
  sdk: ">=3.11.0 <4.0.0"
resolution: workspace

dependencies:
  exceptions:
  freezed_annotation: ^3.1.0
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2

dev_dependencies:
  build_runner: ^2.15.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  givn:
  riverpod_generator: ^4.0.3
  shouldly: ^0.5.0+1
